### PR TITLE
fix: change log message format for addLabel

### LINKED ISSUE #211: Improve log for non existing label warning
**Is your feature request related to a problem? Please describe.**
When we try to add a label, with the `$addLabel` built-in, if that label doesn't exist we create the label and log an warning saying `[warn]: addLabel LABEL_NOT_FOUND was not found in the environment`. This format isn't very friendly.

**Describe the solution you'd like**
Change the log warning to `[warn]: LABEL_NOT_FOUND was not found in the environment`.

**Describe alternatives you've considered**
*None*

**Additional context**
*None*

### PR DESCRIPTION
**Pull request by denizzengin**
## Related issue

Closes #211 

## Type of change

Improvements (non-breaking change without functionality) 

## Checklist

- [x] I have performed a self-review of my code
- [ x] I have ran `task check -f` and have no issues

## Code review and merge strategy (ship/show/ask) 

 [x] Ask: this pull request requires a code review before merge

### CODE REVIEW

**Comment by marcelosousa** [comment]
Many thanks for this contribution @denizzengin ! In the related issue please use "Closes #211" for it to pick up the issue correctly :)

**Review by shay2025 — CHANGES_REQUESTED** [review]
Thanks again for the contribution @denizzengin 🙌 
Could you please improve the log to `log.Printf("[warn]: the %v label was not found in the environment", labelID)`? Thanks!

**Comment by denizzengin** [comment]
> Thanks again for the contribution @denizzengin 🙌 Could you please improve the log to `log.Printf("[warn]: the %v label was not found in the environment", labelID)`? Thanks!

Hi @shay2025 ,
it's done but there is another point in removeLabel function. Should we change here too with same format ?
`log.Printf("[warn]: removeLabel %v was not found in the environemnt", labelID)` to `log.Printf("[warn]:  the %v label was not found in the environemnt", labelID)`

**Comment by shay2025** [comment]
> Hi @shay2025 , it's done but there is another point in removeLabel function. Should we change here too with same format ? `log.Printf("[warn]: removeLabel %v was not found in the environemnt", labelID)` to `log.Printf("[warn]: the %v label was not found in the environemnt", labelID)`
@denizzengin yes, please change with the same format. Thanks for noticing it!

**Review by shay2025 — APPROVED** [review]
Many thanks for this contribution 🙌 . LGTM

**Pull request merged**
